apiVersion: v1
kind: ConfigMap
metadata:
  name: openwebui-static-files
  namespace: rag-demo
data:
  search.html: |
    <!-- Content will be loaded from static/search.html -->
    <!-- Use: kubectl create configmap openwebui-static-files --from-file=search.html=static/search.html --from-file=showcase.html=static/showcase.html --from-file=loader.js=static/loader.js -n rag-demo -->
  showcase.html: |
    <!-- Placeholder -->
  loader.js: |
    <!-- Placeholder -->
